### ISSUE TITLE
Is there a speed issue?

### ISSUE THREAD

**Issue by GeLi1989** [pythongosssss/ComfyUI-WD14-Tagger#11]
I have a 3080 GPU, but it takes 9 seconds to infer from one image to text. Is there a speed issue? 

What should I do to improve speed and shorten time?

thanks

**Comment by ManOrMonster** [comment]
> I found that using the wd-v1-4-vit-tagger v2 model is relatively much faster, while others are very slow

Thanks for this, makes a huge diffrerence.

**Comment by pythongosssss** [comment]
It may be that it is running on CPU (i've never managed to get onnx gpu working myself, but it should use it automatically if you install the correct package...), i'm not sure there is anything I can do to speed things up here, as the actual tagging code is only a couple of lines. Going to close this unless anyone has any suggestions
