### ISSUE TITLE
change model path

### ISSUE THREAD

**Issue by SayanoAI** [pythongosssss/ComfyUI-WD14-Tagger#12]
Is it possible to change the model path using extra_model_paths.yaml? How do you structure it?

**Comment by TomLucidor** [comment]
Seconding this since there are other models to choose from https://civitai.com/models/166561/imagevideo-booru-tagger-wd14-deepdanbooru-e621

**Comment by pythongosssss** [comment]
You can use extra_model_paths.yaml with the key of `wd14_tagger`
thanks to @xingren23
