### ISSUE TITLE
What is the issue here? It was working fine before, but today, I suddenly encountered an error and can't use it. Other plugins are working normally

### ISSUE THREAD

**Issue by wibur0620** [pythongosssss/ComfyUI-WD14-Tagger#16]
Error occurred when executing WD14Tagger|pysssss:

D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

File "D:\AI\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\AI\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\AI\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\AI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 169, in tag
tags.append(wait_for_async(lambda: tag(image, model, threshold, character_threshold, exclude_tags)))
File "D:\AI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 174, in wait_for_async
loop.run_until_complete(run_async())
File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
return future.result()
File "D:\AI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 164, in run_async
r = await async_fn()
File "D:\AI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 47, in tag
model = InferenceSession(name, providers=ort.get_available_providers())
File "D:\AI\ComfyUI\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 430, in __init__
raise fallback_error from e
File "D:\AI\ComfyUI\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 425, in __init__
self._create_inference_session(self._fallback_providers, None)
File "D:\AI\ComfyUI\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
sess.initialize_session(providers, provider_options, disabled_optimizers)

**Comment by wibur0620** [comment]
"My CUDA version is 12.1, and the cuDNN version is 8.9.3

**Comment by justanotherbug** [comment]
i have no startup problems but i get this when it's executing.
got prompt
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "w:\Ai\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.

**Comment by justanotherbug** [comment]
Here is my example of a start-up.


w:\Ai\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-12-01 18:03:08.393228

Prestartup times for custom nodes:
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 32669 MB
xformers version: 0.0.22.post7+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
### Loading: ComfyUI-Impact-Pack (V4.36.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
### Loading: ComfyUI-Inspire-Pack (V0.47.2)
### Loading: ComfyUI-Manager (V1.5.2)
### ComfyUI Revision: 1756 [d19de275] | Released on '2023-11-29'
[SD Prompt Reader] Node version: 1.1.0
[SD Prompt Reader] Core version: 1.3.4
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[VideoHelperSuite] - INFO - ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
Comfyroll Custom Nodes: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
DWPose: Onnxruntime with acceleration providers detected
FizzleDorf Custom Nodes: Loaded
Using xformers cross attention
[tinyterraNodes] Loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Total VRAM 12288 MB, total RAM 32669 MB
xformers version: 0.0.22.post7+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16

[rgthree] Loaded 15 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

Searge-SDXL v4.3.1 in W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 197 nodes successfully.

        "Art is the most intense mode of individualism that the world has known." - Oscar Wilde


Import times for custom nodes:
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLMixSampler.py
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\LatentByRatio.py
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\kohya_hiresfix.py
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\LoadLoraWithTags
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SD-Latent-Upscaler
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\PPF_Noise_ComfyUI
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCMSampler-ComfyUI
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Embedding_Picker
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Lora-Auto-Trigger-Words
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-prompt-info
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg_custom_core
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_PoP
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
   0.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.2 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.3 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.3 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT
   0.5 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.6 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.0 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   1.2 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   1.6 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   2.1 seconds: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: W:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready

**Comment by OracleToes** [comment]
I'm also having this issue, did you ever find some solution?

**Comment by dancemanUK** [comment]
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
outdoors, water, blurry, tree, no_humans, sparkle, depth_of_field, blurry_background, light_particles, branch, bare_tree, bokeh
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.


me,too , 

G:\comfyUI+AnimateDiff\python_embeded>python.exe -s -m pip show onnxruntime-gpu
Name: onnxruntime-gpu
Version: 1.15.1
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: g:\comfyui+animatediff\python_embeded\lib\site-packages
Requires: coloredlogs, flatbuffers, numpy, packaging, protobuf, sympy
Required-by:

**Comment by wibur0620** [comment]
> I'm also having this issue, did you ever find some solution?我也遇到了这个问题，你有没有找到一些解决方案？

I have resolved this issue by downgrading Cuda to version 11.8

**Comment by pythongosssss** [comment]
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html
The latest CUDA version supported by onnxruntime is 11.8, so you'll need to downgrade from 12.1 until they add support
