### ISSUE TITLE
[Feature Request] Support for Joytag

### ISSUE THREAD

**Issue by nomadoor** [pythongosssss/ComfyUI-WD14-Tagger#17]
https://github.com/fpgaminer/joytag
It seems that there is something called Joytag, which is a more versatile visual model, while having the goodness of WD14-tagger.
I was unsure whether to make a feature request in this repo, but I would be very happy if you could support it.

**Comment by dfl** [comment]
I had the same idea. I'm guessing it's primarily a matter of converting that model from safetensors to ONNX, but I'm not experienced with such things.

**Comment by davedaverave** [comment]
Quoting that

**Comment by nomadoor** [comment]
As many of you may already know, it is implemented with this wonderful custom node.
[ComfyUI_VLM_nodes](https://github.com/gokayfem/ComfyUI_VLM_nodes)
