### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

### ISSUE THREAD

**Issue by QueenPuxxi** [pythongosssss/ComfyUI-WD14-Tagger#18]
When I use this node, I encounter an error:

Error occurred when executing WD14Tagger|pysssss:

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

File "C:\Blender_ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Blender_ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Blender_ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 163, in tag
tensor = np.array(tensor, dtype=np.uint8)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Blender_ComfyUI\python_embeded\Lib\site-packages\torch\_tensor.py", line 1032, in __array__
return self.numpy().astype(dtype, copy=False)
^^^^^^^^^^^^

![image](https://github.com/pythongosssss/ComfyUI-WD14-Tagger/assets/136255531/1966421d-3144-4308-ac94-c697e69b0ed4)

**Comment by pythongosssss** [comment]
What is the source node for the image you are sending to the tagger?

**Comment by QueenPuxxi** [comment]
It's "Any Switch (rgthree)".

**Comment by pythongosssss** [comment]
Would you be able to try recreating the issue without these custom nodes in a simpler workflow please as there are a lot of nodes there I dont have

**Comment by snakelenas** [comment]
![image](https://github.com/pythongosssss/ComfyUI-WD14-Tagger/assets/16239691/d0299dd2-6925-4968-8a59-2653570cd89a)

use default workflow can recreating this issue. 

I think it caused by VAE Decoder

> Would you be able to try recreating the issue without these custom nodes in a simpler workflow please as there are a lot of nodes there I dont have
