### ISSUE TITLE
[Feature Request] Add SwinV2 model 

### ISSUE THREAD

**Issue by unLomTrois** [pythongosssss/ComfyUI-WD14-Tagger#24]
Nice extension, any chance to add swinv2 model?

https://huggingface.co/SmilingWolf/wd-v1-4-swinv2-tagger-v2

**Comment by camoody1** [comment]
@unLomTrois I just made two Pull Requests with the necessary code changes to add the swinv2 tagger model. You can check those requests to see the changes if you want to make them yourself. They're super short and simple.
