### ISSUE TITLE
Prompt words are not displayed

### ISSUE THREAD

**Issue by jcling1024** [pythongosssss/ComfyUI-WD14-Tagger#29]
WD14 does not display prompt words after use, prompt words are displayed on the CMD
[picture.zip](https://github.com/pythongosssss/ComfyUI-WD14-Tagger/files/14442179/picture.zip)

**Comment by Erwin11** [comment]
Me too,but I found it cause you update comfyui versions. Downgrade version .
The last OK version is this.
"Add example for how to use WEB_DIRECTORY to add frontend extensions."
SHA: 4a7e751ce667562661135132c1237b5bb82e40d4
https://github.com/comfyanonymous/ComfyUI/commit/4a7e751ce667562661135132c1237b5bb82e40d4

**Comment by wavenyou** [comment]
@pythongosssss WD14 prompt words are displayed on the CMD，web didn't display prompt
