### ISSUE TITLE
Just updated (ComfyUI and all nodes) and no longer seeing option in right-click menu

### ISSUE THREAD

**Issue by ghostsquad** [pythongosssss/ComfyUI-WD14-Tagger#30]
I recently (yesterday) updated ComfyUI and all nodes, and noticed that Tagger is no longer showing up in the right-click menu for images nodes.

![image](https://github.com/pythongosssss/ComfyUI-WD14-Tagger/assets/903488/200c8626-aebf-4e0e-b71a-b960e695d6ac)

**Comment by wangfeng35** [comment]
+1 same here

**Comment by n714** [comment]
same

**Comment by afanfan98** [comment]
How to solve it

**Comment by pythongosssss** [comment]
This should now be resolved if you update

**Comment by afanfan98** [comment]
> 如果您更新，这个问题现在应该可以解决

Still can't solve it

**Comment by ghostsquad** [comment]
It shows up for me. 👍 
![image](https://github.com/pythongosssss/ComfyUI-WD14-Tagger/assets/903488/350a707c-c145-44fd-8222-a71a532b772a)

I'm on commit `a7dd82e668bfaf7fac365a4e73a1ba1acf224fbb` of ComfyUI and commit `ec533b7cf2be1230eddf07ac74faf434ab805b33` of `ComfyUI-WD14-Tagger`.
