### ISSUE TITLE
[Solved] After updated the lastest comfyui version,wd14-tagger nodes not display Tag Words anymore.

### ISSUE THREAD

**Issue by Erwin11** [pythongosssss/ComfyUI-WD14-Tagger#35]
After updated comfyui version to the lastest,wd14-tagger nodes not display Tag Words anymore.
You should downgrade version.

After I check versions one by one. I found it.

![Broken  disable follow_symlinks ](https://github.com/pythongosssss/ComfyUI-WD14-Tagger/assets/6300501/fe60a482-dd4c-4ead-97fc-ab294fa73d0d)
![OK WEB_DIRECTORY](https://github.com/pythongosssss/ComfyUI-WD14-Tagger/assets/6300501/815a856f-209f-486b-96a4-64c1c0c5788a)

The last OK version is this.
Feb 25 is OK.
Add example for how to use WEB_DIRECTORY to add frontend extensions.
SHA: 4a7e751ce667562661135132c1237b5bb82e40d4
https://github.com/comfyanonymous/ComfyUI/commit/4a7e751ce667562661135132c1237b5bb82e40d4

Broken start here.
Feb 25 is broken.
disable follow_symlinks in static serving for security reason (#2902)
SHA: 8d7910cee93e28ec4f222775d86c0a328479630e
https://github.com/comfyanonymous/ComfyUI/commit/8d7910cee93e28ec4f222775d86c0a328479630e

**### I didn't know what happened , It works for me. might be helps.**

**Comment by pythongosssss** [comment]
This should now be resolved if you update
