### ISSUE TITLE
Stopped working after updating

### ISSUE THREAD

**Issue by MrGingerSir** [pythongosssss/ComfyUI-WD14-Tagger#36]
I updated today after having not used ComfyUI in a while, and everything updated well except this custom node. I have since tried uninstalling and reinstalling both by hand (following the directions exactly) and by using the manager in ComfyUI. I have also tried doing the fix option in the manager, but none of this has worked. 
When i load up ComfyUI, i receive the notification in my CMD window of (IMPORT FAILED).

**Comment by pythongosssss** [comment]
Could you please provide the output of the CMD window so I can see what the error is

**Comment by pythongosssss** [comment]
If the error is `SyntaxError: f-string: unmatched '['`, update now I've resolved that

**Comment by MrGingerSir** [comment]
thanks! it was SyntaxError: f-string: unmatched '[', and it works now after updating!
