### ISSUE TITLE
Wd14 tagger re-runs the same image

### ISSUE THREAD

**Issue by wulfila07** [pythongosssss/ComfyUI-WD14-Tagger#72]
Why is the tagger re-running even if I keep the same image loaded (already tagged in a previous run)? Is there a way to prevent it?

**Comment by metsweet999** [comment]
i think this problem is important,
if resolved, can save lot of time when using workflows, especially the ones have lots of nodes was set after the wd14 tagger.

**Comment by metsweet999** [comment]
i think adding "

    @classmethod
    def IS_CHANGED(s, image):
        image_path = folder_paths.get_annotated_filepath(image)
        m = hashlib.sha256()
        with open(image_path, 'rb') as f:
            m.update(f.read())
        return m.digest().hex()

"
to line 204 of "E:\ComfyUI_Mini-1\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py" will work.
i will try it later.

**Comment by filipemeneses** [comment]
Tried to implement `IS_CHANGED` but the image always comes `None` in the argument; also tried to store the image hash when tag is called but when `IS_CHANGED` is called, it's also `None`.

Found out that apparently the back-end isn't authoritative, removing this code from the `wd14tagger.js` solved for me


https://github.com/pythongosssss/ComfyUI-WD14-Tagger/blob/262cfdbd16d5892c0a8fcb2d61439610854aeaea/web/js/wd14tagger.js#L96-L101

**Comment by pythongosssss** [comment]
This should be fixed
