### ISSUE TITLE
The file path to execute the train_network.py script is incorrect

### ISSUE THREAD

**Issue by Joker2020-cmd** [pythongosssss/ComfyUI-WD14-Tagger#95]
code:    #Looking for the training script.
        progpath = os.getcwd()
        nodespath=''
        for dirpath, dirnames, filenames in os.walk(progpath):
             if 'sd-scripts' in dirnames:
               nodespath= dirpath + '/sd-scripts/train_network.py'
               print(nodespath)

D:\software_Download\Python_E\python.exe: can't open file 'E:\\modelsaft\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\custom_nodes\\Lora-Training-in-Comfy\\sd-scripts\\train_network.py': [Errno 2] No such file or directory
Traceback (most recent call last):

**Comment by pythongosssss** [comment]
This looks to be an issue with the extension `Lora-Training-in-Comfy` if you can raise the issue with them
